[package]
name = "flappy-brid"
version = "0.1.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bevy = "0.7"
rand = "0.8.5"

[workspace]
resolver = "2"

[target.wasm32-unknown-unknown]
runner = "wasm-server-runner"
